# Generated by Django 4.1.2 on 2023-03-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("node", "0007_connection_action_connection_bytes_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="connection",
            unique_together={("from_component", "to_component", "action")},
        ),
    ]
