# Generated by Django 4.1.2 on 2023-03-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node", "0012_alter_component_cpu_utilization"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="instance_type",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
