version: "3"

services:
  app:
    build: price_my_cloud
    image: price-my-cloud
    ports:
      - "8080:8080"
    env_file:
      - price_my_cloud/.env
    depends_on:
      - db
    volumes:
      - ./price_my_cloud/src:/src/src
    command: ['python', './manage.py', 'runserver', '0.0.0.0:8080', '--settings=dsm.settings']

  db:
    image: postgres:14
    env_file:
      - price_my_cloud/.env
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_volume:
    external: false
