# Generated by Django 4.1.2 on 2023-02-14 19:20

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("node", "0004_alter_node_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="node.node"
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FlowLogData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("source", models.GenericIPAddressField()),
                ("destination", models.GenericIPAddressField()),
                ("source_port", models.PositiveSmallIntegerField()),
                ("destination_port", models.PositiveSmallIntegerField()),
                ("protocol", models.PositiveSmallIntegerField()),
                ("packet", models.PositiveIntegerField()),
                ("bytes", models.PositiveIntegerField()),
                ("start", models.PositiveIntegerField()),
                ("end", models.PositiveIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[("ACCEPT", "ACCEPT"), ("REJECT", "REJECT")],
                        max_length=255,
                    ),
                ),
                (
                    "log_status",
                    models.CharField(
                        choices=[
                            ("OK", "OK"),
                            ("NODATA", "NODATA"),
                            ("SKIPDATA", "SKIPDATA"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "flow_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aws.flowlog"
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
