# Generated by Django 4.1.2 on 2023-02-11 14:09

import datetime
from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("node", "0002_alter_component_duration_of_operating_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="component",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="componenttype",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="node",
            options={"get_latest_by": "modified"},
        ),
        migrations.RemoveField(
            model_name="component",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="component",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="componenttype",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="componenttype",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="node",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="node",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="component",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="component",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="componenttype",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="componenttype",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="connection",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 2, 11, 14, 9, 13, 546082, tzinfo=datetime.timezone.utc
                ),
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="node",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
    ]
