# Generated by Django 4.1.2 on 2023-02-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node", "0003_alter_component_options_alter_componenttype_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
    ]
