# Generated by Django 4.1.2 on 2023-02-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node", "0004_alter_node_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
