# Generated by Django 4.1.2 on 2023-02-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node", "0005_alter_node_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="component",
            options={},
        ),
        migrations.AddField(
            model_name="component",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="component",
            unique_together={("node", "name")},
        ),
    ]
