# Generated by Django 4.1.2 on 2023-03-08 20:47

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node", "0008_alter_connection_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="cpu_utilization",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="end",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 8, 21, 47, 13, 473161)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="connection",
            name="start",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 8, 21, 47, 23, 682094)
            ),
            preserve_default=False,
        ),
    ]
