# Generated by Django 4.1.2 on 2023-03-08 20:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node", "0009_component_cpu_utilization_connection_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="cpu_utilization",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
