# Generated by Django 4.1.2 on 2023-03-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node", "0014_alter_connection_packets"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="time_of_processing",
            field=models.DurationField(null=True),
        ),
    ]
