# Generated by Django 4.1.2 on 2023-03-22 21:43

from decimal import Decimal
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("node", "0015_node_time_of_processing"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstanceCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("instance_type", models.CharField(max_length=255)),
                (
                    "cost_per_Hour",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=7
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
