# Generated by Django 4.1.2 on 2023-03-22 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("node", "0016_instancecost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instancecost",
            old_name="cost_per_Hour",
            new_name="cost_per_hour",
        ),
    ]
