version: "3"

services:
  app:
    build: distributed_system_mock
    image: distributed-system-mock
    ports:
      - "7000:7000"
    env_file:
      - distributed_system_mock/.env
    depends_on:
      - db
    volumes:
      - ./distributed_system_mock/src:/src/src
    command: ['python', './manage.py', 'runserver', '0.0.0.0:7000', '--settings=dsm.settings']

  db:
    image: postgres:14
    env_file:
      - distributed_system_mock/.env
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_volume:
    external: false
