# Generated by Django 4.1.2 on 2023-02-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aws", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowlogdata",
            name="destination_port",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="flowlogdata",
            name="protocol",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="flowlogdata",
            name="source_port",
            field=models.PositiveIntegerField(),
        ),
    ]
