# Generated by Django 4.1.2 on 2023-02-15 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aws", "0002_alter_flowlogdata_destination_port_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flowlogdata",
            old_name="packet",
            new_name="packets",
        ),
    ]
